### ISSUE TITLE
inotify

### ISSUE THREAD

**Issue by Crushable1278** [dd010101/vyos-jenkins#17]
The build script provided for python3-inotify will build a 0.2.10-1 version of python3-inotify, but it includes a dependency on `nose` that is not present in the official deb.

Interestingly, this package is not found in the Sagitta repo, but is found in Equuleus and Circinus. The packages in Equuleus and Circinus show the same checksums. The Circinus rolling image pulls in the 0.2.10-1 version from the current repo.

If we download the Circinus deb and navigate to `/usr/lib/python3/dist-packages/inotify/resources/` and observe `requirements.txt`, you'll find that the official deb features no line item for `nose`, but the package built from source, specifically against tags `0.2.10-1` and `0.2.10-2`, has a requirement for `nose`.

You can see the removal of the `nose` requirement in 0.2.10-3 here: https://salsa.debian.org/python-team/packages/python-inotify/-/commit/9f3acb91dbe9ceb5d7d73d776cef4e924b255309

I'm not sure how the official deb has accomplished this without manual intervention since the version number is still 0.2.10-1.

Since building an image with the current upstream-built inotify will pull in `python3-nose` that is not found in any of my generated-using-the-official-repo iso images, I propose that the version be moved to 0.2.10-3 at least.

You can see the changelog for the package here, comparing 0.2.10-3 to 0.2.10-1, indicating effectively no change:
https://salsa.debian.org/python-team/packages/python-inotify/-/compare/debian%2F0.2.10-1...debian%2F0.2.10-3?from_project_id=10739&straight=true

We could consider 0.2.10-4, but this version will not build using the Equuleus build container without further modifications to the source.

**Comment by dd010101** [comment]
Is there reason to include python3-inotify apart of the fact the Debian buster doesn't have it? I don't believe there is any secret sauce specific to VyOS. That's why is puzzling to see python3-inotify in current repo.

`0.2.10-1` that isn't `0.2.10-1`? What is going on there? The plot thickens even more if you realize what is the date of python3-inotify in the current repository... The version for current was built before the patch to remove nose existed... They aren't using `0.2.10-3` since that was released after. It doesn't make sense to include python3-inotify anyway since Debian already has it. They did [realize this](https://vyos.dev/T5076) and made corrections for sagitta.

It's also interesting to note they prefer the VyOS repository regardless of Debian version for sagitta/current https://github.com/vyos/vyos-build/commit/4cc1045f24c59594c924e34cfc3c094c64b3058f. This isn't the case for equuleus. Thus they really use the old version for current branch even when bookworm has it... Whatever, it's a mess...

The changes between the versions are very slight so it doesn't matter in the end. The code of inotify didn't change since 0.2.10, those extra versions are changes only for building/testing. Like nose library is used only for testing - it's not included in the installed version.

We can include the newer version if you want but it doesn't change anything since the fixes were made for building/testing on future Debians.

**Comment by Crushable1278** [comment]
I could have sworn I saw the python3-nose package get pulled in on .iso build. As you noted, I am incorrect. I now don't see it being pulled in, therefore this is a meaningless post and a waste of your time. My apologies.

**Comment by dd010101** [comment]
Well you are right, you sight is good indeed.

This vyos was built from official repository:

```
vyos@vyos:~$ apt show python3-inotify
Package: python3-inotify
Version: 0.2.10-1
Status: install ok installed
Priority: optional
Section: python
Source: inotify
Maintainer: Dustin Oprea <myselfasunder@gmail.com>
Installed-Size: 58.4 kB
Depends: python3:any
Homepage: https://github.com/dsoprea/PyInotify
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
...
```

This one was built from vyos-missing:

```
vyos@vyos:~$ apt show python3-inotify
Package: python3-inotify
Version: 0.2.10-1
Status: install ok installed
Priority: optional
Section: python
Source: python-inotify
Maintainer: Debian Python Team <team+python@tracker.debian.org>
Installed-Size: 61.4 kB
Depends: python3-nose, python3:any
Suggests: python-python-inotify-doc
Homepage: https://github.com/dsoprea/PyInotify
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
...
```

It's not used so it increases the size of the image by tiny bit but indeed whatever `0.2.10-1` version VyOS has isn't the `0.2.10-1` Debian version nor any other Debain version...

**Comment by Crushable1278** [comment]
From a code perspective, there are no changes relative to upstream 0.2.10 until you use the debian/0.2.10-5 tag. I think debian/0.2.10-3 is a good compromise to remove the dependency while still allowing for compilation on Buster.

**Comment by dd010101** [comment]
Done
