### ISSUE TITLE
No release file

### ISSUE THREAD

**Issue by ashimov** [dd010101/vyos-jenkins#21]
I did all steps in guide but have problem that my repo is clean

<img width="764" alt="image" src="https://github.com/dd010101/vyos-jenkins/assets/9959703/1a09fd3e-5b10-46f7-9489-8618455609f1">

What i do wrong?

**Comment by dd010101** [comment]
Did you resolve the issue? Is it something we should address in the instructions?

**Comment by Neboer** [comment]
+1 same issue here, after the build, there is no `InRelease` `Release` and `Release.gpg` under `/home/sentrium/web/dev.packages.vyos.net/public_html/repositories/sagitta/dists/sagitta/`.
A few days ago I've built the package and it is just fine, the files are there, but they are missing when I trying to build vyos-jenkins on a new machine today on another server.

**Comment by Neboer** [comment]
I just don't know in what process the folder /home/sentrium/web/dev.packages.vyos.net/public_html/repositories/ was created and becoming an apt repo. Could you please to explain it for me?

**Comment by Neboer** [comment]
Thank you for your fast reply. Jenkins builds are all successful except [wide-dhcpv6 » equuleus] gave an error, which I will mention in another issue later. Or you can get the log [here](https://pastebin.com/8rDv0vkU) .

I've follow your guide and see there **is** something wrong in unicron. here is the [log file](https://termbin.com/fcc1).

**Comment by dd010101** [comment]
The reason there are no .deb files is that every reprepro call fails with `gpgme gave error Pinentry:32870:  Inappropriate ioctl for device`. The reprepro needs to sign every package that's added by your singing key - this is done via the `gpg` package.

Are you sure that your gpg singing key doesn't have passphrase?

What happens if your run `sudo -u jenkins bash -c "echo test | gpg --local-user vyos -as -"` as root. Does it give you output with `-----BEGIN PGP MESSAGE-----` or does it fail or does it ask for passphrase? It should just return the `-----BEGIN PGP MESSAGE-----`....

**Comment by Neboer** [comment]
The output is
```
root@UntilJenkins2:~# sudo -u jenkins bash -c "echo test | gpg --local-user vyos -as -"
gpg: skipped "vyos": No secret key
gpg: signing failed: No secret key
```

**Comment by dd010101** [comment]
Maybe your key is named differently. Try without the name `sudo -u jenkins bash -c "echo test | gpg -as -"`

**Comment by Neboer** [comment]
```
jenkins@UntilJenkins2:/home/neboer$ echo test | gpg -as -
gpg: signing failed: Inappropriate ioctl for device
-----BEGIN PGP MESSAGE-----

gpg: signing failed: Inappropriate ioctl for device
```

**Comment by Neboer** [comment]
I'm in a virtual machine running debian bookworm under ArchLinux using QEMU with virt-manager.

**Comment by dd010101** [comment]
This seem like generic `gpg` challenge. People say running `export GPG_TTY=$(tty)` in your shell before your run the gpg command fixes this issue, does it help you too? For me it just works. I'm also on Debian Bookworm.

**Comment by Neboer** [comment]
```
jenkins@UntilJenkins2:/home/neboer$ export GPG_TTY=$(tty)
jenkins@UntilJenkins2:/home/neboer$ echo test | gpg -as -
gpg: signing failed: Permission denied
-----BEGIN PGP MESSAGE-----

gpg: signing failed: Permission denied
jenkins@UntilJenkins2:/home/neboer$ echo test | gpg -as - -vv
usage: gpg [options] --sign [filename]
jenkins@UntilJenkins2:/home/neboer$ echo test | gpg -vv -as -
gpg: using pgp trust model
gpg: key CC78990F9366550C: accepted as trusted key
gpg: writing to stdout
gpg: pinentry launched (2437343 curses 1.2.1 /dev/pts/1 xterm-256color - 20620/0/5 1006/1006 -)
gpg: signing failed: Permission denied
-----BEGIN PGP MESSAGE-----

gpg: signing failed: Permission denied
```
It seems that `gpg` is trying to write to something into /dev/pts/1 but failed with permission denied.
After some digging on this, I strace it and here is [the log](https://pastebin.com/L1vtXuSN).

Emmm, maybe it is asking for password input but due to lack of permission to write the pts for unknown reason, it cannot write to the terminal for "please input password" things so it just failed.

Can I just delete the password of my jenkins default gpg key or something similar? How to do this or something elase cause this?

**Comment by dd010101** [comment]
You can [remove](https://superuser.com/a/1488214) passphrase.

You can as well just delete the key `gpg --yes --delete-secret-and-public-key <NAME-OR-ID>` and generate new one by the instructions, then you need to update and replace the key ID in `/home/sentrium/web/dev.packages.vyos.net/public_html/repositories/equuleus/conf/distributions` and `/home/sentrium/web/dev.packages.vyos.net/public_html/repositories/sagitta/conf/distributions` with the new one.

**Comment by dd010101** [comment]
I did add more suggestive note about the passphrase, now it should be impossible to be missed. The gpg nudges you to set the passphrase but you can't give in!

Perhaps this was also the issue for @ashimov as well. This explains why would you see successful builds in Jenkins and nothing in `/home/sentrium/web/dev.packages.vyos.net/public_html/repositories` since the reprepro fails in background later. Such behavior requires the reprepro to fail in some way and gpg is the most likely cause.

**Comment by Neboer** [comment]
It works! Thank you!

**Comment by Neboer** [comment]
Please update the title to a more meaningful one so that other people can take it as a reference if they have wrongly set the password like me 🤣

**Comment by Neboer** [comment]
It works! Everything works fine and I have just built the release iso. THAT IS AMAZING!

**Comment by ashimov** [comment]
> Did you resolve the issue? Is it something we should address in the instructions?

Hi!Resolved issue,just wait for build all packages
