### ISSUE TITLE
jenkins package build jobs branch selection

### ISSUE THREAD

**Issue by UnixxSH** [dd010101/vyos-jenkins#29]
First - many thanks to provide such a way to build VyOS, considering the last annoucements they did without proper documentation.

I just wanted to know if there is a way to only build the packages for sagitta for example ? I had to delete the equuleus ones in ./jobs/project-jobs.json, as I do not need packages for 1.3.

Thanks.

**Comment by GurliGebis** [comment]
If you remove the equuleus packages from there, it won't build them.
But, depending on your hardware, the overhead of building both isn't that big.

**Comment by dd010101** [comment]
Most of the equuleus packages don't take much time/resources to build but there are few exceptions like the kernel. Also many small ones will add up. That's why if you don't want equuleus (or sagitta) then it makes sense to add support to exclude it. There is no option to do it as of now.

If you delete "equuleus-only" that's not the whole solution since many packages are shared and to exclude shared packages you would need to adjust the branch regex correctly - not easy to do. Not only in the project-jobs.json but also in docker-container-jobs.json.

Thus I added the option to build only specific branch, check the readme for "**If you want to build only specific branch**" how to use it.

Let me know if this works for you.

**Comment by UnixxSH** [comment]
> Thus I added the option to build only specific branch, check the readme for "**If you want to build only specific branch**" how to use it.

I just tried, and it's working as intended. Thanks for the quick reply !

**Comment by dd010101** [comment]
👍

**Comment by GurliGebis** [comment]
@dd010101 I think `SELECTED_BRANCH_REGEX="(sagitta|current)"` is a problem, since it would mean that it tries to provision `current` for all packages - which would make the provision script fail, since not all of them have a current.
Have you tested that case, with a clean Jenkins? 🙂

**Comment by GurliGebis** [comment]
Or am I missing something

**Comment by dd010101** [comment]
This regex is used only for matching if the branch is applicable at all. This regex isn't used for the pipeline. It only says if branch is applicable at all for further processing. Thus the regex matches for sagitta:
- sagitta, 
- equuleus+sagitta, 
- sagitta+current,
- equuleus+current,
- equuleus+sagitta+current. 

The logic that overrides the pipeline regex is [here](https://github.com/dd010101/vyos-jenkins/blob/master/auto/helper-logic#L248). Thus the pipeline regex is converted for sagitta as follows:
- equuleus+sagitta into sagitta,
- sagitta+current into sagitta+current,
- equuleus+current into current, 
- equuleus+sagitta+current into sagitta+current.
 
Equuleus gets always just equuleus. This is compared only if the branch regex matches thus sagitta only or equuleus only jobs won't even get here, they are excluded before this. There are two kinds of exclusions - jobs is excluded completely or just the piplene regex is reduced. That's why the regex you found exists - to exclude non-shared jobs completely.

Yes I did test and you get all packages correctly and two ISOs if you don't set the branch. I also run the sagitta only and I did check all the combinations for pipeline regex, I also test to add equuleus later to sagitta only. I didn't test equuleus only though. So much testing... I did run the scripts from start to end like 50 times already, so many packages built to be deleted right away! 😄

**Comment by GurliGebis** [comment]
I see 😊

I have optimized it a bit, to make sure the skipped jobs doesn't take up space in the queue - see #30
