### ISSUE TITLE
podman dependencies problem running build-iso.sh

### ISSUE THREAD

**Issue by carlo-luzi** [dd010101/vyos-jenkins#35]
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: libc6 (>= 2.38) but 2.36-9+deb12u7 is to be installed
          Depends: libgpgme11t64 (>= 1.4.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...
Traceback (most recent call last):
I: Checking if packages required for VyOS image build are installed
I: using build flavors directory data/build-flavors
I: Cleaning the build workspace
I: Setting up additional APT entries
I: Configuring live-build
I: Starting image build
  File "/vyos/./build-vyos-image", line 621, in <module>
    cmd("lb build 2>&1")
  File "/vyos/scripts/image-build/utils.py", line 84, in cmd
    raise OSError(f"Command '{command}' failed")
OSError: Command 'lb build 2>&1' failed
ISO build failed
```

Clean and updated Debian 12 install on VM, all automated scripts from 1 to 8 run without problems.

For further reference here build-iso.sh output [build-iso.log](https://github.com/user-attachments/files/16143872/build-iso.log)

**Comment by carlo-luzi** [comment]
I also attach uncron service log [uncron.log](https://github.com/user-attachments/files/16144110/uncron.log)

**Comment by dd010101** [comment]
Yet another build broken by pull request in waiting... 🤔

Sagitta also merged now, so it's resolved? Seems to be working for me...

**Comment by carlo-luzi** [comment]
Three hours ago I restarted the automated sequence and the build was successful. Tomorrow I'll do a test install with the ISO.

**Comment by carlo-luzi** [comment]
It seems to work, as a reference I paste here the versions of some packages affected by the upstream fix:

```
vyos@vyos:~$ dpkg -l | grep -e libgpgme11t64 -e podman -e netavark
ii  netavark                             1.4.0-4.1                        amd64        Rust based network stack for containers
ii  podman                               4.3.1+ds1-8+deb12u1              amd64        engine to run OCI-based containers in Pods
vyos@vyos:~$
```

**Comment by dd010101** [comment]
I have 4.3.1 too.

> As of Debian version 4.9.5+ds1-1 podman increased the dependency on
libc6 and libgpgme11t64.
>  podman : Depends: libc6 (>= 2.38) but 2.36-9+deb12u7 is to be installed
>           Depends: libgpgme11t64 (>= 1.4.1) but it is not going to be installed
> Pin the version to a prior one that requires the old libc.

The commit message of the pin seems wrong to me.... They pinned trixie and this failed since libc is different, so they fixed the pin to what exactly? Not trixie since if it was trixie then the libc difference would still exist...?

I my eyes they fixes the pin so much it stopped working?

**Comment by trystan-s** [comment]
Even their most recent daily rolling build has podman	4.3.1+ds1-8+deb12u1 so it's safe to say their commit didn't work.

**Comment by dd010101** [comment]
http://ftp.debian.org/debian/pool/main/libp/libpod/

No it doesn't exist. So this is cache thing - it's removed from some mirrors?

I see this:

```
[ ]	golang-github-containers-libpod-dev_3.0.1+dfsg1-3+deb11u5_all.deb	2023-12-30 20:15 	1.4M
[ ]	libpod_3.0.1+dfsg1-3+deb11u5.debian.tar.xz	2023-12-29 23:43 	19K
[TXT]	libpod_3.0.1+dfsg1-3+deb11u5.dsc	2023-12-29 23:43 	4.8K
[ ]	libpod_3.0.1+dfsg1.orig.tar.xz	2021-02-24 17:28 	2.1M
[ ]	libpod_4.3.1+ds1-8+deb12u1.debian.tar.xz	2024-03-25 21:37 	20K
[TXT]	libpod_4.3.1+ds1-8+deb12u1.dsc	2024-03-25 21:37 	4.3K
[ ]	libpod_4.3.1+ds1.orig.tar.xz	2022-11-14 00:30 	2.5M
[ ]	libpod_4.9.4+ds1-1.debian.tar.xz	2024-03-28 11:32 	22K
[TXT]	libpod_4.9.4+ds1-1.dsc	2024-03-28 11:32 	5.4K
[ ]	libpod_4.9.4+ds1.orig.tar.xz	2024-03-28 11:32 	2.7M
[ ]	libpod_4.9.5+ds1-1.debian.tar.xz	2024-07-04 21:27 	22K
[TXT]	libpod_4.9.5+ds1-1.dsc	2024-07-04 21:27 	5.4K
[ ]	libpod_4.9.5+ds1.orig.tar.xz	2024-07-04 21:27 	2.7M
[ ]	libpod_5.0.2+ds1-3.debian.tar.xz	2024-05-05 11:54 	24K
[TXT]	libpod_5.0.2+ds1-3.dsc	2024-05-05 11:54 	5.4K
[ ]	libpod_5.0.2+ds1.orig.tar.xz	2024-04-28 18:21 	2.7M
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_amd64.deb	2024-04-01 12:19 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_arm64.deb	2024-04-01 12:24 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_armel.deb	2024-04-01 12:19 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_armhf.deb	2024-04-01 12:24 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_i386.deb	2024-04-01 12:19 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_mips64el.deb	2024-04-01 13:29 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_mipsel.deb	2024-04-01 13:14 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_ppc64el.deb	2024-04-01 12:14 	19K
[ ]	podman-docker_4.3.1+ds1-8+deb12u1_s390x.deb	2024-04-01 12:13 	19K
[ ]	podman-docker_4.9.5+ds1-1_amd64.deb	2024-07-04 22:02 	25K
[ ]	podman-docker_4.9.5+ds1-1_arm64.deb	2024-07-04 21:57 	25K
[ ]	podman-docker_4.9.5+ds1-1_armel.deb	2024-07-04 22:02 	25K
[ ]	podman-docker_4.9.5+ds1-1_armhf.deb	2024-07-04 22:02 	25K
[ ]	podman-docker_4.9.5+ds1-1_i386.deb	2024-07-04 21:57 	25K
[ ]	podman-docker_4.9.5+ds1-1_mips64el.deb	2024-07-05 04:50 	25K
[ ]	podman-docker_4.9.5+ds1-1_ppc64el.deb	2024-07-04 21:57 	25K
[ ]	podman-docker_4.9.5+ds1-1_riscv64.deb	2024-07-05 00:49 	25K
[ ]	podman-docker_4.9.5+ds1-1_s390x.deb	2024-07-04 22:38 	25K
[ ]	podman-docker_5.0.2+ds1-3_amd64.deb	2024-05-05 20:13 	24K
[ ]	podman-docker_5.0.2+ds1-3_arm64.deb	2024-05-05 20:28 	24K
[ ]	podman-docker_5.0.2+ds1-3_armel.deb	2024-05-05 20:59 	24K
[ ]	podman-docker_5.0.2+ds1-3_armhf.deb	2024-05-05 20:59 	24K
[ ]	podman-docker_5.0.2+ds1-3_i386.deb	2024-05-05 20:23 	24K
[ ]	podman-docker_5.0.2+ds1-3_mips64el.deb	2024-05-06 04:17 	24K
[ ]	podman-docker_5.0.2+ds1-3_ppc64el.deb	2024-05-05 20:13 	24K
[ ]	podman-docker_5.0.2+ds1-3_riscv64.deb	2024-05-13 15:29 	24K
[ ]	podman-docker_5.0.2+ds1-3_s390x.deb	2024-05-05 22:07 	24K
[ ]	podman-remote_4.9.5+ds1-1_amd64.deb	2024-07-04 22:02 	7.9M
[ ]	podman-remote_4.9.5+ds1-1_arm64.deb	2024-07-04 21:57 	6.8M
[ ]	podman-remote_4.9.5+ds1-1_armel.deb	2024-07-04 22:02 	6.5M
[ ]	podman-remote_4.9.5+ds1-1_armhf.deb	2024-07-04 22:02 	6.5M
[ ]	podman-remote_4.9.5+ds1-1_i386.deb	2024-07-04 21:57 	6.9M
[ ]	podman-remote_4.9.5+ds1-1_mips64el.deb	2024-07-05 04:50 	5.7M
[ ]	podman-remote_4.9.5+ds1-1_ppc64el.deb	2024-07-04 21:57 	6.3M
[ ]	podman-remote_4.9.5+ds1-1_riscv64.deb	2024-07-05 00:49 	6.6M
[ ]	podman-remote_4.9.5+ds1-1_s390x.deb	2024-07-04 22:38 	6.8M
[ ]	podman-remote_5.0.2+ds1-3_amd64.deb	2024-05-05 20:13 	7.2M
[ ]	podman-remote_5.0.2+ds1-3_arm64.deb	2024-05-05 20:28 	6.2M
[ ]	podman-remote_5.0.2+ds1-3_armel.deb	2024-05-05 20:59 	5.8M
[ ]	podman-remote_5.0.2+ds1-3_armhf.deb	2024-05-05 20:59 	5.8M
[ ]	podman-remote_5.0.2+ds1-3_i386.deb	2024-05-05 20:23 	6.3M
[ ]	podman-remote_5.0.2+ds1-3_mips64el.deb	2024-05-06 04:17 	5.2M
[ ]	podman-remote_5.0.2+ds1-3_ppc64el.deb	2024-05-05 20:13 	5.7M
[ ]	podman-remote_5.0.2+ds1-3_riscv64.deb	2024-05-13 15:29 	6.0M
[ ]	podman-remote_5.0.2+ds1-3_s390x.deb	2024-05-05 22:07 	6.1M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_amd64.deb	2023-12-30 20:10 	9.1M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_arm64.deb	2023-12-30 20:20 	7.8M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_armel.deb	2023-12-30 20:25 	7.8M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_armhf.deb	2023-12-30 20:15 	7.8M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_i386.deb	2023-12-30 20:15 	8.4M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_mips64el.deb	2023-12-30 22:17 	7.0M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_mipsel.deb	2023-12-30 22:02 	7.0M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_ppc64el.deb	2023-12-30 20:10 	7.5M
[ ]	podman_3.0.1+dfsg1-3+deb11u5_s390x.deb	2023-12-30 20:36 	8.1M
[ ]	podman_4.3.1+ds1-8+deb12u1_amd64.deb	2024-04-01 12:19 	10M
[ ]	podman_4.3.1+ds1-8+deb12u1_arm64.deb	2024-04-01 12:24 	8.8M
[ ]	podman_4.3.1+ds1-8+deb12u1_armel.deb	2024-04-01 12:19 	9.0M
[ ]	podman_4.3.1+ds1-8+deb12u1_armhf.deb	2024-04-01 12:24 	8.9M
[ ]	podman_4.3.1+ds1-8+deb12u1_i386.deb	2024-04-01 12:19 	9.6M
[ ]	podman_4.3.1+ds1-8+deb12u1_mips64el.deb	2024-04-01 13:29 	8.0M
[ ]	podman_4.3.1+ds1-8+deb12u1_mipsel.deb	2024-04-01 13:14 	8.1M
[ ]	podman_4.3.1+ds1-8+deb12u1_ppc64el.deb	2024-04-01 12:14 	8.4M
[ ]	podman_4.3.1+ds1-8+deb12u1_s390x.deb	2024-04-01 12:13 	9.2M
[ ]	podman_4.9.5+ds1-1_amd64.deb	2024-07-04 22:02 	12M
[ ]	podman_4.9.5+ds1-1_arm64.deb	2024-07-04 21:57 	11M
[ ]	podman_4.9.5+ds1-1_armel.deb	2024-07-04 22:02 	11M
[ ]	podman_4.9.5+ds1-1_armhf.deb	2024-07-04 22:02 	11M
[ ]	podman_4.9.5+ds1-1_i386.deb	2024-07-04 21:57 	11M
[ ]	podman_4.9.5+ds1-1_mips64el.deb	2024-07-05 04:50 	9.6M
[ ]	podman_4.9.5+ds1-1_ppc64el.deb	2024-07-04 21:57 	10M
[ ]	podman_4.9.5+ds1-1_riscv64.deb	2024-07-05 00:49 	11M
[ ]	podman_4.9.5+ds1-1_s390x.deb	2024-07-04 22:38 	11M
[ ]	podman_5.0.2+ds1-3_amd64.deb	2024-05-05 20:13 	12M
[ ]	podman_5.0.2+ds1-3_arm64.deb	2024-05-05 20:28 	10M
[ ]	podman_5.0.2+ds1-3_armel.deb	2024-05-05 20:59 	10M
[ ]	podman_5.0.2+ds1-3_armhf.deb	2024-05-05 20:59 	10M
[ ]	podman_5.0.2+ds1-3_i386.deb	2024-05-05 20:23 	11M
[ ]	podman_5.0.2+ds1-3_mips64el.deb	2024-05-06 04:17 	9.3M
[ ]	podman_5.0.2+ds1-3_ppc64el.deb	2024-05-05 20:13 	10M
[ ]	podman_5.0.2+ds1-3_riscv64.deb	2024-05-13 15:29 	10M
[ ]	podman_5.0.2+ds1-3_s390x.deb	2024-05-05 22:07 	11M
```

**Comment by trystan-s** [comment]
From that link I only see versions 3.0.1, 4.3.1, 4.9.5, and 5.0.2

**Comment by dd010101** [comment]
Yep, I see no point why would Debian keep old versions around. Imagine the capacity that would require... The fix with pin to old version is thus wrong since it pins version that is subject for removal and soon will be deleted from all mirrors.

How to fix it properly? I see only one way - build podman 4.9.5 from source.

**Comment by dd010101** [comment]
Is VyOS team aware of this? I guess then need to have some backlog task to fix this properly eventually since pinning to 4.9.4 forever isn't long term solution thus building from source is the way forward. This would change the priority of such task...

**Comment by dd010101** [comment]
Because of bug https://vyos.dev/T5829

> I'm sure they're not. With the status of our accounts, who will let them know?

I have no accounts anymore, everything on VyOS side was deleted 😄

**Comment by dd010101** [comment]
>  I can't seem to find any relevant commits from the podman PR or release notes indicating it was fixed. I'm sure this just means I'm not looking properly.

This could be fixed by the 4.7.0 for example - hard to find out. Only the c-po knows how he concluded the newer version fixes this.

> I'm essentially trying to see if Bookworm's version took in the fix from the time it was reported as an issue until the April release of 4.3.1. Maybe it's not an issue anymore and we can go back to Bookworm's?

Then it easier to look at the Debian changes - do you see relevant back-port? The only newer version is the latest the [changelog](https://salsa.debian.org/debian/libpod/-/blob/debian/bookworm/debian/changelog?ref_type=heads#L1-7) the [patch](https://salsa.debian.org/debian/libpod/-/blob/debian/bookworm/debian/patches/fix-removed-container-handling.patch?ref_type=heads).

> Someone would need to reproduce the test case from T5829 on a new build - or the [20240710](https://github.com/vyos/vyos-rolling-nightly-builds/releases/tag/1.5-rolling-202407100021) nightly.

The funny thing is that I can't make it work even with previous sagitta build...

![obrazek](https://github.com/dd010101/vyos-jenkins/assets/91662885/cdd99699-dfc9-453d-b06a-94616ef2d055)

Yes, it's broken with 4.3.1 but also with 4.7.4 so this doesn't tell much...

The steps:

```
# you need internet access for the container pull
configure
set system name-server 8.8.8.8
set interfaces ethernet eth0 address dhcp
commit

exit

add container image alpine

configure

set container name alp01 image 'alpine'
set container name alp01 network NET01 address '10.0.0.12'
set container network NET01 prefix '10.0.0.0/24'
commit

set container network NET01 prefix '2001:db8::/64'
set container name alp01 network NET01 address '2001:db8::12'
commit
```

**Comment by carlo-luzi** [comment]
Thank you all very much, in the end maybe this is the price to pay in building a  "FrankenDebian”

**Comment by dd010101** [comment]
@Crushable1278

> Something I do in my Sagitta+ images is further extend the debranding and strip the hardcoded mention of VyOS from the reported version string

Something like this https://github.com/dd010101/vyos-build/commit/a6aada10e66c3d70776a7111bfd49098bb278bd8? 

![vyos](https://github.com/dd010101/vyos-jenkins/assets/91662885/0f6d9e5e-6d3a-4497-91d9-851db74966d5)

There are countless mentions of "VyOS" but the point isn't to get rid of all of them, it's enough to get rid of the most visible ones in each stage (install/boot/login). The version command is also good candidate. There are also pointless mentions like these https://github.com/vyos/vyos-1x/blob/sagitta/op-mode-definitions/show-system.xml.in#L126. Where the name would be easily substituted by generic term, it's obviously not made to be de-branded.

> All in all, I'm immeasurably disappointed that a bug was found, a commit was added to allegedly fix said bug, but no smoketest was ever written to ensure that the bug remained or was ever verifiably fixed.

I would hoped the the fix worked at least for while and then it brake again. This isn't blocking bug though. You can still use the containers with dual-stack you just need to define both IPv4 and IPv6 ranges for network in one commit, if you define network only with IPv4 and then IPv6 then it fails but you can create new network with both and reassign it to all containers - lot of legwork but workable.

My experience with smoketest is - that it creates way more false-positives then it catches bugs. Like identical test failing on one machine and not failing on other, running out of memory, race condition between commit/check... It could be better...

I also understand that different functionalities have different priority and perhaps non-breaking container bugs aren't top priority for VyOS and thus they don't warrant the same attention like writing test for each bug as other parts do. You can confirm this by looking at the test https://github.com/vyos/vyos-1x/blob/sagitta/smoketest/scripts/cli/test_container.py the containers have lot of functionality and options and only few are tested. Funny thing is - there are couple test and one of the test is "test_dual_stack_network" yet this one will pass because it does IPv4+IPv6 and not the IPv4 then IPv6 😄.

**Comment by dd010101** [comment]
New custom build script - https://github.com/vyos/vyos-build/pull/709/files as expected. Work in progress.

**Comment by dd010101** [comment]
Sagitta podman package was added https://github.com/vyos/vyos-build/pull/719.
Yet the build is broken - because of https://github.com/vyos/vyos-build/pull/721, waiting...

**Comment by dd010101** [comment]
```
19:52:12  + cd podman
19:52:12  + echo 'I: installing dependencies'
19:52:12  I: installing dependencies
19:52:12  + make install.tools
19:52:12  /usr/bin/bash: line 1: go: command not found
19:52:12  /usr/bin/bash: line 1: go: command not found
19:52:12  env: ‘go’: No such file or directory
19:52:12  env: ‘go’: No such file or directory
```

It's failing for me since the freshly build sagitta container is broken with the go path. So I don't think it's redundant - why do you think it's redundant?

**Comment by dd010101** [comment]
This was [discussed before](https://github.com/dd010101/vyos-jenkins/discussions/10#discussioncomment-9619502), the skel is blocked in non-interactive shell and thus anything in there is disregarded.

Thus the build is broken unless you run it interctivelly and the Jenkins doesn't.
