### ISSUE TITLE
Unsure of how to run smoketests

### ISSUE THREAD

**Issue by RSully** [dd010101/vyos-jenkins#48]
Hi, I have been using this to build ISOs for both branches successfully using the automated method. It isn't clear to me what exact steps I need to run to be able to run the smoke tests. I read through the README but it seems like it is more tailored for manual building or such, or I am just confused by something obvious. If I am in the `/opt/vyos-jenkins` directory, what do I need to do to run the smoketests?

**Comment by dd010101** [comment]
Since there is no automated way, then you would need to follow the generic instructions. You need to clone the vyos-build, put your ISO into specific directory with specific name, install the dependencies and then you can run it from vyos-build repo. The automated scripts don't help you much, they just give you ISO with vyos-1x-smoketest installed thus you need to prepare the environment yourself.

**Comment by dd010101** [comment]
I did update the section to more reflect current state and give more direct instructions related to the automated scripts. The method is the same though - you need to create the testing environment manually.
