### ISSUE TITLE
Sagitta's netfilter doesn't build

### ISSUE THREAD

**Issue by dutty5** [dd010101/vyos-jenkins#52]
netfilter under sagitta fails to build. Looks like referring missing dependencies:
```
Err:9 http://deb.debian.org/debian bookworm/main amd64 libcdt5 amd64 2.42.2-7+b3
    404  Not Found [IP: 146.75.122.132 80]
Err:11 http://deb.debian.org/debian bookworm/main amd64 libaom3 amd64 3.6.0-1
    404  Not Found [IP: 146.75.122.132 80]
Err:57 http://deb.debian.org/debian bookworm/main amd64 liblab-gamut1 amd64 2.42.2-7+b3
    404  Not Found [IP: 146.75.122.132 80]
Err:64 http://deb.debian.org/debian bookworm/main amd64 graphviz amd64 2.42.2-7+b3
    404  Not Found [IP: 146.75.122.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/graphviz/libcdt5_2.42.2-7%2bb3_amd64.deb  404  Not Found [IP: 146.75.122.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/a/aom/libaom3_3.6.0-1_amd64.deb  404  Not Found [IP: 146.75.122.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/graphviz/liblab-gamut1_2.42.2-7%2bb3_amd64.deb  404  Not Found [IP: 146.75.122.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/graphviz/graphviz_2.42.2-7%2bb3_amd64.deb  404  Not Found [IP: 146.75.122.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
I manually checked a couple of other debian mirrors. Looks like there is no such packages versions there as well. Version typo?

**Comment by dutty5** [comment]
Never mind, installed fresh vyos-jenkins, and it worked.

**Comment by dd010101** [comment]
This is caused by outdated apt cache in the vyos-build docker container. Thus if you want to fix it without fresh setup you can run "Build now" for the vyos-build-container jobs manually via Jenkins and this fixes the issue by rebuilding vyos-build containers. Wait until the vyos-build-container is done and then rerun netfilter and it works.

Root cause is the fact that Debian released new version of those specific packages (and removed the previous version) thus the apt cache it oudated but it's bit strange the netfilter job doesn't call apt update, seems like oversight. The build script is pulled from official repository so it's too much work to fix such minor issue. It's not bad idea to rebuild the vyos-build container from time to time anyway.
