### ISSUE TITLE
Using script to populate jenkins

### ISSUE THREAD

**Issue by GurliGebis** [dd010101/vyos-jenkins#6]
Just an idea that popped into my head, when I noticed the jenkins script folder.
Would it be possible to use a script to load all the packages into jenkins?

**Comment by dd010101** [comment]
Yes, that's my ultimate goal, I started with something small just to get familiar with it. I plan to make script that will seed Jenkins jobs and queue first build, this should expedite the setup process by a lot - I don't plan to script everything, since the small things don't take too long to do by hand, just the jobs since there are many of them and it's tedious.

**Comment by GurliGebis** [comment]
I hope to try and get time to follow the setup described here some time next week.
I plan (if nothing gets in the way), to write scripts that does the steps, instead of doing them manually - if possible, that might be useful (nothing promised yet)

**Comment by dd010101** [comment]
It would be great to have script for most of steps but that's not something I planning to do, so if you would make some progress that would be nice.

**Comment by GurliGebis** [comment]
I will see what I can do, once I get to it 🙂

**Comment by dd010101** [comment]
See [readme](https://github.com/dd010101/vyos-jenkins#multibranch-pipelines-by-script) **Multibranch Pipelines (by script)** and [seed-jobs.sh](https://github.com/dd010101/vyos-jenkins/blob/master/jenkins-scripts/seed-jobs.sh) script to see how to populate Jenkins jobs and launch first build automatically.
