### ISSUE TITLE
Using github.io as a repo to store the packages

### ISSUE THREAD

**Issue by GurliGebis** [dd010101/vyos-jenkins#9]
It looks like it is possible to use github.io to store a debian repository. (Example here: `https://github.com/adelolmo/adelolmo.github.io`)

Would it be an idea to do that - that way we can use it to make the packages available publicly, without having to worry about bandwidth costs?

**Comment by dd010101** [comment]
I don't see what would stop you from doing that. The resulting packages are just static files on webserver so there is basically no requirement to host them anywhere.

The github hosting has issue though since it's intended for small static sites thus they have [limitations](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits) in place to avoid abuse via other unwanted use cases. I suspect it will work until you hit these limitations.

**Comment by GurliGebis** [comment]
I see, in that case, it isn't a good idea 🙂
